### ISSUE TITLE
Add environmental settings

### ISSUE THREAD

**Issue by KevinDanikowski** [amclin/react-project-boilerplate#107]
A production level app will require qa, dev, prod, and potentially other environments. 

publicRuntimeConfig is what we would need to use in the next.config.js (needs to be created). I recommend we use dotenv and use `APP_ENV` . 

I've found the code and am putting it here. `src/utils/dotenv`:
```js
const fs = require('fs');
const dotenv = require('dotenv');
const dotenvExpand = require('dotenv-expand');

const APP_ENV = process.env.APP_ENV;
const appDirectory = fs.realpathSync(process.cwd());

// The order of loading files is:
// 1. Local overrides (.env.local)
// 2. Env specific (ie. .env.production)
// 3. Default (.env)
const dotenvFiles = [
  // Don't include `.env.local` for `test` environment
  // since normally you expect tests to produce the same
  // results for everyone
  APP_ENV !== 'test' && `${appDirectory}/.env.local`,
  `${appDirectory}/.env.${APP_ENV}`,
  `${appDirectory}/.env`,
].filter(Boolean);

dotenvFiles.forEach(dotenvFile => {
  if (fs.existsSync(dotenvFile)) {
    dotenvExpand(
      dotenv.config({
        path: dotenvFile,
      })
    );
  }
});
```

And in the next.config.js in the root dir 
```js
const nextConfig = {
  // assetPrefix, use if you need to change roof asset location
  serverRuntimeConfig: {
    // Will only be available on the server side
  },
  publicRuntimeConfig: {
    // Will be available on both server and client
    ...config,
  },
}
```

**Comment by amclin** [comment]
Ideally the apps generated here run in docker containers and those images are built to be environment-agnostic. That means any values that need to be provided to the runtime are provided as pass-through environment variables from outside the Docker image (aka, not through .env files)

**Comment by KevinDanikowski** [comment]
Took a bit of research, but next.js config is run even after build (so during start after it's been built) to make sure it brings in publicRuntimeConfig. See second comment in https://github.com/zeit/next.js/issues/6906 , the reason I had to look into this is because webpack removes process.env , and so some unique solutions have been designed to get around this (see https://www.freecodecamp.org/news/how-to-implement-runtime-environment-variables-with-create-react-app-docker-and-nginx-7f9d42a91d70/ ). Can you take a quick look and let me know what you prefer to do. I believe the publicRuntimeConfig is made to be the environmental variables so that it uses what ever the process.env is at start (and during build if you wish).

**Comment by KevinDanikowski** [comment]
@amclin  I'm bumping this because I believe it's important and future PRs will be affected by this. Please take a look at the above when you get a chance.

**Comment by amclin** [comment]
Let's go with the dot-env pattern. It works well (as long as the .env files are not checked into source) and the pa

We'll want to exclude the .env files in generated projects through the gitignore, and also include a reference example where an argument is passed to the Docker runtime stage and passed through as an environment variable for Node.

**Comment by KevinDanikowski** [comment]
@amclin Great to hear, I did a pattern where the .env supports multiple environments and has a local .env override. It will be in my apollo PR, you will see.

**Comment by amclin** [comment]
@KevinDanikowski do you mind keeping them separate? It makes it easier to reflect changes in the changelog and easier to manage history when changes are small.
