### ISSUE TITLE
Review jsx-props-no-spreading

### ISSUE THREAD

**Issue by amclin** [amclin/react-project-boilerplate#118]
Investigate if it is warranted to change the props spreading rule (jsx-props-no-spreading) in light of:
https://github.com/yannickcr/eslint-plugin-react/issues/2439

We are using props-spreading with an explicit exception in the higher-order-component within _app.js when following the NextJS recommendation implementation of how to implement wrappers:
https://github.com/amclin/react-project-boilerplate/pull/114/files#diff-3d22b72961e012d82100ecc93f26b509R26

This rule has been updated in eslint-plugin-react v 7.17:
https://github.com/amclin/react-project-boilerplate/pull/115

**Comment by KevinDanikowski** [comment]
AFter discussion it was said that we should just use individual //eslint-disable-next-line. There are now plentiful examples in the app and we can probably close this.
