### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by KevinDanikowski** [amclin/react-project-boilerplate#125]
It is likely this app will require some sort of authentication, i'd like to layout some research here. 

The most common authentication method would be the use of OAuth with JWT (json web tokens) stored in local storage. 

Local Storage/JWT benefits over use as cookies:
1. The benefit of local storage/ JWTs over cookies is they allow meta data to be added (hence the JSON part). They can also store data related to the user (such as an ID or what have you) which reduces server load since it will not need an additional SQL look up. The most critical example may be the use of user permissions.
2. The same API can be used for mobile apps (or other various apps) since one does not need to worry about looking for browser cookies on the mobile app api request. 
3. cookie size matters, JWT size does not. cookie size over 8kb can cause a 400 error on Node 10.15+ versions without adding the max_header_size flag to increase it ( was 80kb until node v10.15+). Further, large cookie sizes can break cookies
4. Cross site request forgery (XSRF) is not an issue if stored in local storage.
5. Signed protection: It appears to prevent modification of the token. 
6. Limited man-in-the-middle-attacks. Though SSL should prevent MITM attacks, OAuth 2.0 uses a short timeframe for token usability and generates a new token after the fact, reducing the time span that MITM attacks are possible.
7. XSS code injection attacks are a known vulnerability, react by default protects against this except in passing down props, thus a JWT should never be passed down as props. 
8. to prevent against stealing a JWT, use shorter timeframes.
9. Suggested that JWTs should only be used for a matter of less than a minute. 
10. **Potentially large benefit benefit if we should ever use it**: We can potentially share this auth token access with an API that allows other apps to access this users bank data (potentially a future endeavor).  
11. Fully scalable, whereas cookies become more difficult as scaling continues.
12. You may hear of JWT being encrypted (JWE), this is only necessary if the JWT holds secret information
13. **One Major Downside:** JWT hijacking to pose as a user, best prevention mechanism is reduce the timespan to a shorter timespan. Though this is not fullproof, a user can still be faked if someone gets a hold of the JWT. (SessionId hijacking can also occur). Best prevention is just use SSL.

Benefit of session cookies over JWTs:
1. Easier to use / implement
2. Has a standard
3. Supposedly no vulnerabilities as compared to JWT (not sure what that means, slide deck didn't detail)
4. Not vulnerable to XSS (Any external dependencies / JS file page requests could bring in an XSS attack making the cookie vulnerable if you use JWTs)
5. **Strongest Benefit** is keeping credentials on server side just associated with sessionId. This would require a cashing infrastructure though. 

**Recommended Solution**: Use JWT tokens with OAuth 2.0 and short expiration times. 

Resources: 
https://dzone.com/articles/cookies-vs-tokens-the-definitive-guide
https://stackoverflow.com/questions/33644499/what-does-it-mean-when-they-say-react-is-xss-protected
https://stackoverflow.com/questions/34259248/what-if-jwt-is-stolen
https://speakerdeck.com/rdegges/jwts-suck

**Comment by amclin** [comment]
Great analysis and a good start for a project-specific discussion, but I'm going to close this as outside the scope of what this public is attempting to achieve.
