### ISSUE TITLE
.babelrc's babel/preset-env conflicts with next/babel.

### ISSUE THREAD

**Issue by oqx** [amclin/react-project-boilerplate#127]
Issue here: https://github.com/zeit/next.js/issues/8175#issuecomment-532659499

`babel/preset-env` with `next/babel` will result in instantiation issues with class components. Class components are still necessary in order to extend wrappers(app, doc) and utilize NextJS lifecycle methods.

Adding `preset-env` to `next/babel` fixed it for me (per linked comment):
```
"presets": [
    [
      "next/babel",
      {
        "preset-env": { "targets": { "node": "current" } }
      }
    ]
  ]
```

**Comment by KevinDanikowski** [comment]
@oqx  I have that in one of my PRs, @amclin  please merge or add comments to fix when you get a chance.

**Comment by KevinDanikowski** [comment]
this can be closed
