### ISSUE TITLE
npx amclin-create-react-app error

### ISSUE THREAD

**Issue by tinkerboyy** [amclin/react-project-boilerplate#22]
issue while executing npx amclin-create-react-app

![image](https://user-images.githubusercontent.com/8486748/66612224-b406cb80-eb86-11e9-9fba-93869814ef42.png)

**Comment by amclin** [comment]
@tinkerboyy can you include the full log please? The screenshot provided isn’t enough to identify where the error is happening.

**Comment by tinkerboyy** [comment]
@amclin that's the only 1 line log.

**Comment by amclin** [comment]
@tinkerboyy can you also provide the version of NPM and Node you are using?

**Comment by tinkerboyy** [comment]
> @tinkerboyy can you also provide the version of NPM and Node you are using?

i think i have 2 versions of node installed on my machine. now i switched to latest.
it works fine now.

**Comment by amclin** [comment]
I'm going to close this since it works with newer versions of Node, but I will add additional build targets to the CICD pipeline so that multiple versions of node get tested with each code change.
