### ISSUE TITLE
"npx amclin-create-react-app" fails with unexpected token '{'

### ISSUE THREAD

**Issue by CarreraPHP** [amclin/react-project-boilerplate#26]
"npx amclin-create-react-app" fails with unexpected token '{' as show below 

![thumbnail_image001](https://user-images.githubusercontent.com/422070/66846917-2b29ce80-ef90-11e9-965a-8db87e0da6e5.png)

Changing the syntax of catch statement from ![thumbnail_image002](https://user-images.githubusercontent.com/422070/66846916-2a913800-ef90-11e9-9d42-3f6a7f252f09.png) to ![thumbnail_image004](https://user-images.githubusercontent.com/422070/66846914-2a913800-ef90-11e9-8b39-cd916b565f11.png) the issue got resolved.

**Comment by CarreraPHP** [comment]
Issue raises in Windows, but not in mac.

**Comment by amclin** [comment]
This is unlikely a Windows vs Mac issue. It is more likely that this fails on older versions of Node. Similar was reported in #22

**Comment by CarreraPHP** [comment]
@amclin, U are right. I didn't think of it that way.
